[pull] master from OpenMW:master (#7)
* Remove GTest and ExternalProject from FindGMock.cmake

* Return to CC0-licensed appdata metadata

* Fix crash on startup

* Do not allow write variant of string as local variable

To be consitent with read where it's not allowed.

* Add tests for ESM::Variant

* Make AddItem's quantity overflow on negative numbers

* Store CustomData and ContainerStore as unique_ptr

* Add move ctor and assignment operator to RefData

* Use CRTP to define CustomData clone function

* Restore old aiming for melee combat

* Fix targeted scripts losing their targets when rearranging your load order

* Fix FetchContent Bullet with MSVC

* Add file to BSA

* De-hardcode references to mesh files used by the sky.

* Do not compare hash in tests

Different std libraries have different implementation that produce different
results for the same values.

* Use std::variant for ESM::Variant implementation

* Update changelog

* Implement #3983 - Add page to the wizard with links to buy morrowind

* Add a coverity scan

* Attempt to fix #5942

Closes OpenMW/openmw#5942
This is an attempt to apply the fix suggested by @Capostrophic

* Use clang 9 for linux builds on travis

* Send travis notifications only for main repo master

* Add Audio settings to openmw-launcher

* Account for waterwalking when updating position. Otherwise we might
trace down the actor at waterlevel at the wrong coordinate.

Triggered by multimark mod with waterwalking effect.

* Change (again) the way SetPos behave.

Instead of registering the desired change of position and rely on
physics simulation to apply it to the world, immediately change the
position in the world without reset the simulation.

* Make Coverity happy about A2C

Initialise member variable

* Unlock mutex on return to avoid hang

* Check for decompression error code

* Avoid division by zero

* Fix uninitialized variables

* Add bound for pointers cache size, as it specified in docs

* Add bound for UI scale factor, as it specified in docs

* Do not use unchecked value in calculations

* Use conventional names for atan2 arguments

* Remove annotation which does not work

* Collada user documentation

* Update OSX deployment target to 10.14

To support std::variant

* Catch exceptions in ResolutionListener

* Remove unused forward declarations

* Use override instead of virtual

* Constify a few things

* Use the number of logical cores on the CI on OSX

* Add setting to allow following creatures to find path over water surface

* Allow water walking actors to find path over water surface

* Don't perform a hit test outside the page's bounds

* Use `rule` instead of `only`

only/except will likely be deprecated: https://docs.gitlab.com/ee/ci/yaml/README.html#onlyexcept-basic

* Install curl in the coverity job

* Fix an off-by-one in loadscpt

* Fix the path for the coverity build

* Use different cache keys for different macOS builds

* Print ccache stats for macOS builds

* Massively increase coverity's timeout

* Only build openmw in coverity

* initial commit

* Add shared UBO

* Brighter point lights and light fade

* Cutoff conditional in light shader

* Switch to integer, uint not reliable in GLSL 120

* Code review cleanup, add setting documentation

* Missed redundant formatting changes

* Enable groundcover lighting for non FFP

* More formatting, OpenCS cells are unbroken

* Ambient luminance threshold setting

* Switch to shared layout, some rewording

* Changelog entry

* Don't break NV shaders

* Fix incorrect minimum ambient

* in-game settings, some require restart

* Finalize settings, torch fix

* Update settings when using fallback

* Shader cleanup, fix indicies

* Make life not suck for whoever wants to edit lighting shaders

* use true default settings

* fix race condition with sun uniform

* clear up force shaders and make it less convoluted

* Fixed error in calculating viewspace sun dir, minor cleanup

* Code review fixes, remove implicit GLSL casts

* `cd` into the build directly to upload coverity logs

* Do not use infinite area cost

Division by zero causes float value to be infinite. When infinite cost is
multiplied by zero distance the result is NaN. After this pathfinding algorithm
state is broken.

* Add walk and swim flags when corresponding speed is positive

This allows to avoid finding path over area that will should have infinite
cost (area_cost = area_cost_factor / area_speed).

* Extend variables range to avoid integer overflow

* Fix uninitialized fields in the essimporter

* An another attempt to suppress Coverity warning about mkstemp

* Join variables declaration and usage

* Fix uninitialized variables in the LightManager

* Fix uninitialized field in the mouse event

* Remove redundant qualifiers

* Remove outdated field - remnant from earlier implementation

* Remove bogus warning. It is a normal situation for projectiles to be
in-flight after the caster is gone.

* Move container unresolving to the separate method

* Set idle priority for navmesh generation thread

Support Linux, Windows, FreeBSD.

* Validate GUI scaling and place it to the launcher

* Follow up MR 722: do not apply mPositionOffset twice when we teleport.

Previous MR change the meaning of mPositionOffset: it is now just a log
of relative movement that were already applied to allow the physics
simulation to catch up, instead of changes that needs to be applied. As
such, after a teleport we need to reset it. Also, since mWorldPosition
is already with the offset we should not update its value in
applyPositionOffset().

* Attempt to fix MacOS beta shared runners.

I think they changed the tag a week ago without notifying us.

* Maybe make -f flag work

Why can't -f just do what the manual says? Why do we even have a pre-existing build directory sometimes? We don't cache it, and artifacts are only supposed to be accessible within the same pipeline.

* Limit pointers cache size to avoid possible bad_alloc errors

* Re-add dropped struct keyword to fix build.

rtprio is both a struct and a function, so we need to be explicit.

../../../components/misc/thread.cpp:53:9: error: must use 'struct' tag
to refer to type 'rtprio' in this scope
rtprio prio;
^
struct
/usr/include/sys/rtprio.h:91:5: note: struct 'rtprio' is hidden by a
non-type declaration of 'rtprio' here
int     rtprio(int, pid_t, struct rtprio *);
^
1 error generated.

* Install ccache before run on macOS

* Fix once and for all™ coverity's schedule

- According to https://gitlab.com/OpenMW/openmw/-/jobs/1176801332 there is no
  need to `cd` into build, since coverity will generate a `cov-int` folder
  in the current folder.
- Don't run other jobs by default during scheduled runs.
- Add a missing terminal quote to coverity's upload command.

* Another fallout from MR 722: objects were treated like actors by
accident. Net effect was that calls to Move/MoveWorld didn't update
position of collision object.

* Add some validation for bsa parsing

This should fix #5955

* Lighting Patch

Fixes build errors with older OSG builds and some issues with 'shared' layout.
Bring back ambient in inventory through lightmodel instead of sun ambient, mirrors scene ambient/sunlight relationship.
Forces shaders when certain lighting methods are enabled and finalize settings.
Correctly override sun for localmap.

* Now that the lighting issue has been fixed, we can now enable active grid by default (which is guarded by distant land).

* String setting to CSMPrefs, part of dehardcoding animation files

* QLineEdit for setting base animation files

* Clean up MSVC warnings

* Don't clobber game log file when we collect a stack trace.

When the crash catcher catch a signal it forks to collect data about its
parent. In the process the child reinitialize the log file, which ends
up empty.

* Fix a read head-buffer-overflow in esm

The check forgot to account for the terminal zero.

* Fix various warnings found by clang

- unused alias
- inefficient use of push_back
- exceptions not inheriting from std::exception
- weird use of a comma
- value compared against itself

* Use isnan

* Fix an another portion of Coverity warnings

* An actor needs not be in active cell. As such we can't use
PhysicsSystem::getActor() to determine that a ptr is not actor.

* Fix headtracking while invisible

* Fix the compilation

* Various improvements to the COLLADA format asset pipeline page. Added images. Added more information on how to define textkeys. Always use all capitals for the COLLADA format name. Barebones subsections for materials and collisions.

* Finish the section on how to set up collision shapes in Blender.

* Do not replace equivalent navmesh tiles

* Finish the section on materials setup.

* Don't use a vec3 if only two components get read

* MGE XE-like stomping

* Explain stomp constants

* Control stomping via settings.

* Do not track last build revision in RecastMeshManger

mLastBuildRevision == mRevision with current use cases does not happen. But
even if this will happen when another use case will be added it does not save
much computation. The most expensive operation is not adding objects to the
MeshBuilder but to optimize resulting navmesh that will happen anyway in
MeshBuilder::create call.

* Remove unnecessary relation between updateCompoundObject and RecastMeshObject

* Detect and ignore updates for oscillating objects

To avoid triggering NavMesh update when RecastMesh change should not change
NavMesh.

Based on the following assumption:
Given a set of transformations and a bounding shape for all these
tranformations, a new object transformation that does not change this
bounding shape also should not change navmesh if for all of this object
transformations resulting navmesh tiles are equivalent

The idea is to report back to RecastMeshManager all changes of NavMesh if there
are any assiciated with RecastMesh version. So we know the last time when
RecastMesh change resulted into the NavMesh change. When later report shows
that there was no NavMesh change for a new RecastMesh version we can assume
that any object transformation within the same bounding box should not change
NavMesh.

* Do not suppress fixed MyGUI warnings

* Fix double -> float conversions

* Fix dead code

* Do not declare unused variables

* Do not leave variables without initialization, even in execution paths where they are unused

* Do not assign negative values to unsigned variables

* Cast double constant to float explicitely

* Allow OSX to fail for now

* Fix node masks signed/unsigned mismatch

* Disable controllers for found sheath meshes (bug #5975)

* Build windows in scheduled tasks

This should solve disappearing nigthlies

* Build even more windows

* Revert Xcode sdk version from 11.6 to 10.2

* don't forget to close the audio device after you're done with it.

* Revert CMAKE_OSX_SYSROOT as this interferes with the gitlab ci builds.

* Clamp vertex lighting before interpolation

Fixes a regression in which pass lighting was clamped after being passed
to fragment shader. For correct FFP emulation, we need to clamp the result
in vertex shader. When clamping after interpolation, negative lights in
particular have a much more drastic effect.

* Don't run `brew uninstall` outside of travis-ci

* Use algorithms to add/remove listener to SpellList

* Add move constructor to MWMechanics::Spells

* Remove noexcept specifier from CreatureCustomData move ctor

C++17 doesn't allow to declare defaulted move ctor with not matching
exception specification to the calculated one:
/Users/eddie/Downloads/BUILD/openmw-master/apps/openmw/mwclass/creature.cpp:63:9: error:
      exception specification of explicitly defaulted move constructor does not
      match the calculated one
        CreatureCustomData(CreatureCustomData&& other) noexcept = default;
        ^

http://wg21.link/p1286r2 makes this possible in C++20 and newer compilers
already have it working even with -std=c++17 but older onces give an error.

* Revert "Build even more windows"

This reverts commit e3d3b97da04ca1622b29be555e77716182e79272.

* Revert "Build windows in scheduled tasks"

This reverts commit 44ca708e12b923d056532e9a77f5350034011341.

* Change travis script back to how it was. To avoid compiler error from old clang version.

* Use a char instead of a string in find() where possible

This was done via PVS Studio ( https://pvs-studio.com ),
and should provide a super-duper-marginal performance boost \o/

* Merge branch 'minor_aicombat' into 'master'

Minor optimization in aicombat.cpp

See merge request OpenMW/openmw!737

(cherry picked from commit f1d19035cccfff2523faad0d4e4d96cd3ddae2e6)

bbbfc520 Minor optimization in aicombat.cpp
237b34a6 Fix style
a14911cb Fix indentation

* Don't log a warning for reading to the end of the subrecord

* Massively simplify the worst Bash ever

* Declare separate constructors with const reference and rvalue arguments for OscillatingRecastMeshObject

* Build everything during the coverity scan

This should fix the 404 on the download page

* Fix ToggleBorders

* Fix typo

Hopefully this will actually let us make better use of shadow bounds,
but I wouldn't count on it.

* Fix NiUVController UV offset calculations (bug #5995)

* Fix a heap overflow in loadpgrd.cpp

* Use higher level transformations in UVController

Co-authored-by: Andrei Kortunov <andrei.kortunov@yandex.ru>
Co-authored-by: elsid <elsid.mail@gmail.com>
Co-authored-by: Alexander Olofsson <ace@haxalot.com>
Co-authored-by: psi29a <psi29a@gmail.com>
Co-authored-by: AnyOldName3 <krizdjali+gitlab@gmail.com>
Co-authored-by: Evil Eye <malusluminis@hotmail.com>
Co-authored-by: CedricMocquillon <cedric.mocquillon@sage.com>
Co-authored-by: Matjaž Lamut <matjaz.lamut@gmail.com>
Co-authored-by: tess <2687892-TescoShoppah@users.noreply.gitlab.com>
Co-authored-by: jvoisin <julien.voisin@dustri.org>
Co-authored-by: Jonas Tobias Hopusch <git@jotoho.de>
Co-authored-by: Simon Meulenbeek <simonmeulenbeek@gmail.com>
Co-authored-by: fredzio <chardon.frederic@gmail.com>
Co-authored-by: glassmancody.info <glassmancody.info@gmail.com>
Co-authored-by: unelsson <unelsson@gmail.com>
Co-authored-by: Jacob Turnbull <jacob@turnbulltech.com>
Co-authored-by: Petr Mikheev <ptmikheev@gmail.com>
Co-authored-by: Alexei Dobrohotov <alex462002@gmail.com>
Co-authored-by: AnyOldName3 <krizdjali+github@gmail.com>
Co-authored-by: Hristos N. Triantafillou <me@hristos.triantafillou.us>
Co-authored-by: nighthawk469 <nick.crawford1234@gmail.com>
Co-authored-by: Roman Siromakha <elsid@users.noreply.github.com>
Co-authored-by: Dobrohotov Alexei <alexdobrohotov@yandex.ru>